import { connection } from "next/server";
import { Award, Coins, Network, RefreshCw, Trophy, UsersRound } from "lucide-react";
import { EmptyState, MetricCard, PageHeader, StatusPill } from "@/components/module-ui";
import { db } from "@/lib/db";
import { requirePermission } from "@/lib/access-control";
import { formatDate, formatMoney, statusTone } from "@/lib/format";
import { deliverRankAwardAction, recalculateRanksAction, updateCommissionStatusAction, updateRankBonusStatusAction } from "./actions";

const commissionLabels = { PENDING: "Pendiente", APPROVED: "Aprobada", PAID: "Pagada", REVERSED: "Reversada" } as const;

export default async function AmbassadorsPage() {
  await requirePermission("AMBASSADORS"); await connection();
  const [ambassadors, ranks, commissions, bonuses, awards] = await Promise.all([
    db.ambassadorProfile.findMany({ orderBy: { affiliatedAt: "desc" }, include: { member: true, sponsor: { include: { member: true } }, referrals: true, investors: true, rankHistory: { orderBy: { achievedAt: "desc" } } } }),
    db.rankDefinition.findMany({ orderBy: { sortOrder: "asc" } }),
    db.commissionEntry.findMany({ take: 100, orderBy: { createdAt: "desc" }, include: { ambassador: { include: { member: true } } } }),
    db.rankBonusPayment.findMany({ take: 100, orderBy: { period: "desc" }, include: { ambassador: { include: { member: true } }, rank: true } }),
    db.rankAward.findMany({ orderBy: { earnedAt: "desc" }, include: { ambassador: { include: { member: true } }, rank: true } }),
  ]);
  const pendingCommission = commissions.filter((item) => item.status === "PENDING").reduce((sum, item) => sum + Number(item.amount), 0);
  return <><PageHeader eyebrow="Red comercial" title="Embajadores" description="Red de patrocinio, comisiones, carrera, bonos mensuales y premios." action={<form action={recalculateRanksAction}><button className="primary-button"><RefreshCw size={17} />Recalcular rangos</button></form>} />
    <section className="module-metrics"><MetricCard label="Embajadores activos" value={String(ambassadors.filter((item) => item.status === "ACTIVE").length)} detail="Perfiles habilitados" icon={UsersRound} /><MetricCard label="Rangos" value={String(ranks.length)} detail="Bronce a Diamante" icon={Trophy} /><MetricCard label="Comisión pendiente" value={formatMoney(pendingCommission)} detail="Por aprobar" icon={Coins} /><MetricCard label="Premios obtenidos" value={String(awards.length)} detail={`${awards.filter((item) => !item.deliveredAt).length} por entregar`} icon={Award} /></section>

    <section className="module-panel portal-section"><div className="module-toolbar"><div><h2>Plan de carrera</h2><p>El plazo máximo se cuenta desde la afiliación. Rubí conserva la regla vigente de cinco directos.</p></div></div><div className="table-wrap module-table"><table><thead><tr><th>Rango</th><th>Socios</th><th>Directos</th><th>Puntos directos</th><th>Volumen</th><th>Plazo</th><th>Bono mensual</th><th>Premio</th></tr></thead><tbody>{ranks.map((rank) => <tr key={rank.code}><td><strong>{rank.name}</strong></td><td>{rank.memberCount}</td><td>{rank.directCount}</td><td>{rank.directPoints}</td><td className="money">{formatMoney(rank.totalPoints)}</td><td>{rank.deadlineMonths} meses</td><td className="money">{formatMoney(rank.monthlyBonus)}</td><td>{rank.rewardName ?? "—"}</td></tr>)}</tbody></table></div></section>

    <section className="module-panel portal-section"><div className="module-toolbar"><div><h2>Directorio y rango actual</h2><p>Relación directa de patrocinio y ascensos registrados</p></div></div>{ambassadors.length === 0 ? <EmptyState icon={Network} title="Aún no hay embajadores" description="Asigna el perfil Embajador para iniciar la red." /> : <div className="table-wrap module-table"><table><thead><tr><th>Código</th><th>Embajador</th><th>Patrocinador</th><th>Directos</th><th>Rango</th><th>Último ascenso</th><th>Estado</th></tr></thead><tbody>{ambassadors.map((item) => <tr key={item.id}><td className="money">{item.referralCode}</td><td>{item.member.firstName} {item.member.lastName}</td><td>{item.sponsor ? `${item.sponsor.member.firstName} ${item.sponsor.member.lastName}` : "Raíz de red"}</td><td>{new Set([...item.referrals.map((entry) => entry.memberId), ...item.investors.map((entry) => entry.memberId)]).size}</td><td>{ranks.find((rank) => rank.code === item.currentRank)?.name ?? "Sin rango"}</td><td>{formatDate(item.rankHistory[0]?.achievedAt)}</td><td><StatusPill tone={item.status === "ACTIVE" ? "success" : "warning"}>{item.status === "ACTIVE" ? "Activo" : "Pendiente"}</StatusPill></td></tr>)}</tbody></table></div>}</section>

    <section className="module-panel portal-section"><div className="module-toolbar"><div><h2>Comisiones de red</h2><p>Generación 1 es el patrocinador directo; generaciones 2 a 8 son indirectas.</p></div></div>{commissions.length ? <div className="table-wrap module-table"><table><thead><tr><th>Embajador</th><th>Nivel</th><th>Monto</th><th>Puntos</th><th>Estado</th><th>Fecha</th><th>Acciones</th></tr></thead><tbody>{commissions.map((item) => <tr key={item.id}><td>{item.ambassador.member.firstName} {item.ambassador.member.lastName}</td><td>{item.generation === 1 ? "Directa" : `Generación ${item.generation}`}</td><td className="money">{formatMoney(item.amount)}</td><td>{item.points}</td><td><StatusPill tone={statusTone(item.status)}>{commissionLabels[item.status]}</StatusPill></td><td>{formatDate(item.createdAt)}</td><td><div className="row-actions">{item.status === "PENDING" && <form action={updateCommissionStatusAction.bind(null, item.id, "APPROVED")}><button className="row-action">Aprobar</button></form>}{item.status === "APPROVED" && <form action={updateCommissionStatusAction.bind(null, item.id, "PAID")}><button className="row-action">Marcar pagada</button></form>}{!["PAID", "REVERSED"].includes(item.status) && <form action={updateCommissionStatusAction.bind(null, item.id, "REVERSED")}><button className="row-action danger-link">Reversar</button></form>}</div></td></tr>)}</tbody></table></div> : <EmptyState icon={Coins} title="No hay comisiones generadas" description="Se crearán cuando una venta alcance el pago requerido para comisionar." />}</section>

    <section className="module-panel portal-section"><div className="module-toolbar"><div><h2>Bonos mensuales de rango</h2><p>Se generan al recalcular para el rango vigente del periodo.</p></div></div>{bonuses.length ? <div className="table-wrap module-table"><table><thead><tr><th>Embajador</th><th>Rango</th><th>Periodo</th><th>Monto</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{bonuses.map((item) => <tr key={item.id}><td>{item.ambassador.member.firstName} {item.ambassador.member.lastName}</td><td>{item.rank.name}</td><td>{formatDate(item.period)}</td><td className="money">{formatMoney(item.amount)}</td><td><StatusPill tone={statusTone(item.status)}>{commissionLabels[item.status]}</StatusPill></td><td><div className="row-actions">{item.status === "PENDING" && <form action={updateRankBonusStatusAction.bind(null, item.id, "APPROVED")}><button className="row-action">Aprobar</button></form>}{item.status === "APPROVED" && <form action={updateRankBonusStatusAction.bind(null, item.id, "PAID")}><button className="row-action">Marcar pagado</button></form>}</div></td></tr>)}</tbody></table></div> : <EmptyState icon={Trophy} title="No hay bonos de rango" description="Recalcula los rangos para generar el bono mensual de quienes califican." />}</section>

    <section className="module-panel portal-section"><div className="module-toolbar"><div><h2>Premios por categoría</h2><p>Reconocimientos obtenidos y control de entrega.</p></div></div>{awards.length ? <div className="table-wrap module-table"><table><thead><tr><th>Embajador</th><th>Rango</th><th>Premio</th><th>Obtenido</th><th>Estado</th><th></th></tr></thead><tbody>{awards.map((item) => <tr key={item.id}><td>{item.ambassador.member.firstName} {item.ambassador.member.lastName}</td><td>{item.rank.name}</td><td>{item.rank.rewardName ?? "Reconocimiento"}</td><td>{formatDate(item.earnedAt)}</td><td><StatusPill tone={item.deliveredAt ? "success" : "warning"}>{item.deliveredAt ? "Entregado" : "Por entregar"}</StatusPill></td><td>{!item.deliveredAt && <form action={deliverRankAwardAction.bind(null, item.id)}><button className="row-action">Registrar entrega</button></form>}</td></tr>)}</tbody></table></div> : <EmptyState icon={Award} title="No hay premios obtenidos" description="Los premios aparecerán cuando un embajador ascienda de rango." />}</section>
  </>;
}
