import { connection } from "next/server";
import { Award, BadgeCheck, BadgeDollarSign, CircleDollarSign, Coins, GitBranch, Network, RefreshCw, RotateCcw, Sparkles, Target, Trophy, UsersRound } from "lucide-react";
import { EmptyState, MetricCard, PageHeader, StatusPill } from "@/components/module-ui";
import { db } from "@/lib/db";
import { requirePermission } from "@/lib/access-control";
import { formatDate, formatMoney, statusTone } from "@/lib/format";
import { deliverRankAwardAction, recalculateRanksAction, updateCommissionStatusAction, updateRankBonusStatusAction } from "./actions";

const commissionLabels = { PENDING: "Pendiente", APPROVED: "Aprobada", PAID: "Pagada", REVERSED: "Reversada" } as const;

export default async function AmbassadorsPage() {
  await requirePermission("AMBASSADORS"); await connection();
  const [ambassadors, ranks, commissions, bonuses, awards, programs, commissionRules] = await Promise.all([
    db.ambassadorProfile.findMany({ orderBy: { affiliatedAt: "desc" }, include: { member: true, sponsor: { include: { member: true } }, referrals: true, investors: true, rankHistory: { orderBy: { achievedAt: "desc" } } } }),
    db.rankDefinition.findMany({ orderBy: { sortOrder: "asc" } }),
    db.commissionEntry.findMany({ take: 100, orderBy: { createdAt: "desc" }, include: { ambassador: { include: { member: true } } } }),
    db.rankBonusPayment.findMany({ take: 100, orderBy: { period: "desc" }, include: { ambassador: { include: { member: true } }, rank: true } }),
    db.rankAward.findMany({ orderBy: { earnedAt: "desc" }, include: { ambassador: { include: { member: true } }, rank: true } }),
    db.program.findMany({ where: { active: true }, orderBy: { cashPrice: "asc" }, include: { financingPlans: { where: { active: true }, orderBy: { downPayment: "asc" } } } }),
    db.commissionRule.findMany({ where: { active: true }, orderBy: [{ generation: "asc" }, { version: "desc" }] }),
  ]);
  const pendingCommission = commissions.filter((item) => item.status === "PENDING").reduce((sum, item) => sum + Number(item.amount), 0);
  const directRule = (programId: string, mode: "CASH" | "CREDIT") => commissionRules.find((rule) => rule.programId === programId && rule.mode === mode && rule.generation === 0);
  const unilevelRules = Array.from(new Map(commissionRules.filter((rule) => !rule.programId && !rule.mode && rule.generation >= 1).map((rule) => [rule.generation, rule])).values());
  return <><PageHeader eyebrow="Red comercial" title="Embajadores" description="Red de patrocinio, comisiones, carrera, bonos mensuales y premios." action={<form action={recalculateRanksAction}><button className="primary-button"><RefreshCw size={17} />Recalcular rangos</button></form>} />
    <section className="module-metrics"><MetricCard label="Embajadores activos" value={String(ambassadors.filter((item) => item.status === "ACTIVE").length)} detail="Perfiles habilitados" icon={UsersRound} /><MetricCard label="Rangos" value={String(ranks.length)} detail="Bronce a Diamante" icon={Trophy} /><MetricCard label="Comisión pendiente" value={formatMoney(pendingCommission)} detail="Por aprobar" icon={Coins} /><MetricCard label="Premios obtenidos" value={String(awards.length)} detail={`${awards.filter((item) => !item.deliveredAt).length} por entregar`} icon={Award} /></section>

    <section className="ambassador-visual-section portal-section" aria-labelledby="direct-bonus-title"><div className="visual-section-heading"><div><span className="eyebrow">Bono directo</span><h2 id="direct-bonus-title">Comisiones por recomendación</h2><p>Valores y puntos configurados por programa y modalidad de compra.</p></div><BadgeDollarSign aria-hidden="true" size={28} /></div><div className="direct-bonus-grid">{programs.map((program) => { const cash = directRule(program.id, "CASH"); const credit = directRule(program.id, "CREDIT"); const initial = program.financingPlans[0]?.downPayment; return <article className="direct-bonus-card" key={program.id}><div className="direct-bonus-card-header"><strong>{program.name}</strong><span>{cash?.points ?? credit?.points ?? 0} puntos</span></div><div className="direct-bonus-values"><div><small>Pago al contado</small><b>{formatMoney(program.cashPrice)}</b><span>Comisión: {cash?.fixedAmount ? formatMoney(cash.fixedAmount) : "No configurada"}</span></div><div><small>Financiado · inicial</small><b>{initial ? formatMoney(initial) : "Sin plan"}</b><span>Comisión: {credit?.fixedAmount ? formatMoney(credit.fixedAmount) : "No configurada"}</span></div></div></article>; })}</div><div className="points-note"><Target aria-hidden="true" size={19} /><p><strong>Los puntos son unidades de clasificación.</strong> Se acumulan en cada afiliación y alimentan el avance de rangos, la red y los bonos.</p></div></section>

    <section className="ambassador-visual-section portal-section" aria-labelledby="unilevel-title"><div className="visual-section-heading"><div><span className="eyebrow">Bono indirecto unilevel</span><h2 id="unilevel-title">Participación por generaciones</h2><p>Porcentajes vigentes de la red, calculados sobre la base definida para cada comisión.</p></div><GitBranch aria-hidden="true" size={28} /></div>{unilevelRules.length ? <div className="generation-ladder">{unilevelRules.map((rule) => <article key={rule.id} className="generation-step"><span>Generación {rule.generation}</span><strong>{Number(rule.percentage ?? 0).toLocaleString("es-PE", { maximumFractionDigits: 2 })}%</strong><small>{rule.generation === 1 ? "Nivel directo" : "Nivel indirecto"}</small></article>)}</div> : <p className="inline-empty">No hay reglas unilevel activas para mostrar.</p>}<div className="visual-explainer"><CircleDollarSign aria-hidden="true" size={20} /><span>La comisión total se obtiene sumando las generaciones activas y se registra individualmente en el libro de comisiones.</span></div></section>

    <section className="ambassador-visual-section portal-section" aria-labelledby="leadership-title"><div className="visual-section-heading"><div><span className="eyebrow">Club de liderazgo</span><h2 id="leadership-title">Ascenso a Diamante</h2><p>Cada escalón representa crecimiento, liderazgo y proyección económica.</p></div><Sparkles aria-hidden="true" size={28} /></div><div className="rank-journey">{ranks.map((rank) => <article className="rank-journey-card" key={rank.code}><div className="rank-journey-badge">{rank.logoUrl ? <img src={rank.logoUrl} alt={`Logo ${rank.name}`} /> : <Trophy aria-hidden="true" size={21} />}</div><span>Rango {rank.sortOrder}</span><h3>{rank.name}</h3><p>{rank.rewardDescription || "Consolida tu red y avanza hacia el siguiente objetivo."}</p><div><b>{Number(rank.totalPoints).toLocaleString("es-PE")} puntos</b><small>{rank.memberCount} socios · {rank.directCount} directos</small></div><strong>{rank.rewardName ?? "Reconocimiento"}</strong></article>)}</div></section>

    <section className="module-panel portal-section"><div className="module-toolbar"><div><h2>Plan de carrera</h2><p>El plazo máximo se cuenta desde la afiliación. Rubí conserva la regla vigente de cinco directos.</p></div></div><div className="table-wrap module-table"><table><thead><tr><th>Rango</th><th>Socios mínimo</th><th>Socios directos mínimo</th><th>Puntos directos mínimo</th><th>Puntos de volumen</th><th>Plazo</th><th>Bono mensual</th><th>Premio</th></tr></thead><tbody>{ranks.map((rank) => <tr key={rank.code}><td><span className="rank-name-cell">{rank.logoUrl && <img src={rank.logoUrl} alt={`Logo ${rank.name}`} />}<strong>{rank.name}</strong></span></td><td>{rank.memberCount}</td><td>{rank.directCount}</td><td>{rank.directPoints}</td><td className="money">{Number(rank.totalPoints).toLocaleString("es-PE")}</td><td>{rank.deadlineMonths} meses</td><td className="money">{formatMoney(rank.monthlyBonus)}</td><td>{rank.rewardName ?? "—"}</td></tr>)}</tbody></table></div></section>

    <section className="module-panel portal-section"><div className="module-toolbar"><div><h2>Directorio y rango actual</h2><p>Relación directa de patrocinio y ascensos registrados</p></div></div>{ambassadors.length === 0 ? <EmptyState icon={Network} title="Aún no hay embajadores" description="Asigna el perfil Embajador para iniciar la red." /> : <div className="table-wrap module-table"><table><thead><tr><th>Código</th><th>Embajador</th><th>Patrocinador</th><th>Directos</th><th>Rango</th><th>Último ascenso</th><th>Estado</th></tr></thead><tbody>{ambassadors.map((item) => <tr key={item.id}><td className="money">{item.referralCode}</td><td>{item.member.firstName} {item.member.lastName}</td><td>{item.sponsor ? `${item.sponsor.member.firstName} ${item.sponsor.member.lastName}` : "Raíz de red"}</td><td>{new Set([...item.referrals.map((entry) => entry.memberId), ...item.investors.map((entry) => entry.memberId)]).size}</td><td>{ranks.find((rank) => rank.code === item.currentRank)?.name ?? "Sin rango"}</td><td>{formatDate(item.rankHistory[0]?.achievedAt)}</td><td><StatusPill tone={item.status === "ACTIVE" ? "success" : "warning"}>{item.status === "ACTIVE" ? "Activo" : "Pendiente"}</StatusPill></td></tr>)}</tbody></table></div>}</section>

    <section className="module-panel portal-section"><div className="module-toolbar"><div><h2>Comisiones de red</h2><p>Generación 1 es el patrocinador directo; generaciones 2 a 8 son indirectas.</p></div></div>{commissions.length ? <div className="table-wrap module-table"><table><thead><tr><th>Embajador</th><th>Nivel</th><th>Monto</th><th>Puntos</th><th>Estado</th><th>Fecha</th><th>Acciones</th></tr></thead><tbody>{commissions.map((item) => <tr key={item.id}><td>{item.ambassador.member.firstName} {item.ambassador.member.lastName}</td><td>{item.generation === 1 ? "Directa" : `Generación ${item.generation}`}</td><td className="money">{formatMoney(item.amount)}</td><td>{item.points}</td><td><StatusPill tone={statusTone(item.status)}>{commissionLabels[item.status]}</StatusPill></td><td>{formatDate(item.createdAt)}</td><td><div className="row-actions">{item.status === "PENDING" && <form action={updateCommissionStatusAction.bind(null, item.id, "APPROVED")}><button className="row-action approve" type="submit"><BadgeCheck size={16} aria-hidden="true" />Aprobar</button></form>}{item.status === "APPROVED" && <form action={updateCommissionStatusAction.bind(null, item.id, "PAID")}><button className="row-action edit-link" type="submit"><CircleDollarSign size={16} aria-hidden="true" />Marcar pagada</button></form>}{!["PAID", "REVERSED"].includes(item.status) && <form action={updateCommissionStatusAction.bind(null, item.id, "REVERSED")}><button className="row-action danger-link" type="submit"><RotateCcw size={16} aria-hidden="true" />Reversar</button></form>}</div></td></tr>)}</tbody></table></div> : <EmptyState icon={Coins} title="No hay comisiones generadas" description="Se crearán cuando una venta alcance el pago requerido para comisionar." />}</section>

    <section className="module-panel portal-section"><div className="module-toolbar"><div><h2>Bonos mensuales de rango</h2><p>Se generan al recalcular para el rango vigente del periodo.</p></div></div>{bonuses.length ? <div className="table-wrap module-table"><table><thead><tr><th>Embajador</th><th>Rango</th><th>Periodo</th><th>Monto</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{bonuses.map((item) => <tr key={item.id}><td>{item.ambassador.member.firstName} {item.ambassador.member.lastName}</td><td>{item.rank.name}</td><td>{formatDate(item.period)}</td><td className="money">{formatMoney(item.amount)}</td><td><StatusPill tone={statusTone(item.status)}>{commissionLabels[item.status]}</StatusPill></td><td><div className="row-actions">{item.status === "PENDING" && <form action={updateRankBonusStatusAction.bind(null, item.id, "APPROVED")}><button className="row-action approve" type="submit"><BadgeCheck size={16} aria-hidden="true" />Aprobar</button></form>}{item.status === "APPROVED" && <form action={updateRankBonusStatusAction.bind(null, item.id, "PAID")}><button className="row-action edit-link" type="submit"><CircleDollarSign size={16} aria-hidden="true" />Marcar pagado</button></form>}</div></td></tr>)}</tbody></table></div> : <EmptyState icon={Trophy} title="No hay bonos de rango" description="Recalcula los rangos para generar el bono mensual de quienes califican." />}</section>

    <section className="module-panel portal-section"><div className="module-toolbar"><div><h2>Premios por categoría</h2><p>Reconocimientos obtenidos y control de entrega.</p></div></div>{awards.length ? <div className="table-wrap module-table"><table><thead><tr><th>Embajador</th><th>Rango</th><th>Premio</th><th>Obtenido</th><th>Estado</th><th></th></tr></thead><tbody>{awards.map((item) => <tr key={item.id}><td>{item.ambassador.member.firstName} {item.ambassador.member.lastName}</td><td>{item.rank.name}</td><td>{item.rank.rewardName ?? "Reconocimiento"}</td><td>{formatDate(item.earnedAt)}</td><td><StatusPill tone={item.deliveredAt ? "success" : "warning"}>{item.deliveredAt ? "Entregado" : "Por entregar"}</StatusPill></td><td>{!item.deliveredAt && <form action={deliverRankAwardAction.bind(null, item.id)}><button className="row-action approve" type="submit"><Award size={16} aria-hidden="true" />Registrar entrega</button></form>}</td></tr>)}</tbody></table></div> : <EmptyState icon={Award} title="No hay premios obtenidos" description="Los premios aparecerán cuando un embajador ascienda de rango." />}</section>
  </>;
}
