import { connection } from "next/server";
import { CircleDollarSign, Clock3, Eye, ReceiptText } from "lucide-react";
import { EmptyState, MetricCard, PageHeader, StatusPill } from "@/components/module-ui";
import { db } from "@/lib/db";
import { formatDate, formatMoney, statusTone } from "@/lib/format";
import { PaymentCreateDialog, PaymentManageDialog, PaymentVoucherAttach } from "./payment-dialogs";
import { requirePermission } from "@/lib/access-control";
import { SubmissionReview } from "./submission-review";
import { paymentConceptLabels } from "@/lib/payment-concepts";

export default async function PaymentsPage() {
  await requirePermission("PAYMENTS");
  await connection();
  const [payments, submissions, overdue, paid, sales] = await Promise.all([
    db.payment.findMany({ take: 100, orderBy: [{ paidAt: "desc" }, { confirmedAt: "desc" }], include: { sale: { include: { member: true, program: true } }, submission: { select: { id: true, voucherUrl: true } } } }),
    db.paymentSubmission.findMany({ where: { status: "PENDING" }, orderBy: { submittedAt: "asc" }, select: { id: true, saleId: true, concept: true, amount: true, submittedAt: true, voucherUrl: true, sale: { include: { member: true, program: true } } } }), db.installment.count({ where: { status: "OVERDUE" } }), db.payment.aggregate({ where: { status: "CONFIRMED" }, _sum: { amount: true } }),
    db.sale.findMany({ where: { status: { not: "CANCELLED" } }, orderBy: { createdAt: "desc" }, include: { member: true, program: true } }),
  ]);
  const history = payments.length ? await db.auditLog.findMany({ where: { entityType: "Payment", entityId: { in: payments.map((payment) => payment.id) } }, orderBy: { createdAt: "desc" }, take: 500 }) : [];
  const historyByPayment = new Map<string, typeof history>(); for (const item of history) historyByPayment.set(item.entityId, [...(historyByPayment.get(item.entityId) ?? []), item]);
  const saleOptions = sales.map((sale) => ({ id: sale.id, code: sale.code, member: `${sale.member.firstName} ${sale.member.lastName}`, program: sale.program.name, mode: sale.mode, status: sale.status }));
  return <><PageHeader eyebrow="Finanzas" title="Pagos" description="Registro, corrección, anulación y aplicación automática de pagos." action={<PaymentCreateDialog sales={saleOptions} />} />
    <section className="module-metrics"><MetricCard label="Por validar" value={String(submissions.length)} detail="Comprobantes pendientes" icon={ReceiptText} /><MetricCard label="Cuotas vencidas" value={String(overdue)} detail="Requieren seguimiento" icon={Clock3} /><MetricCard label="Pagos confirmados" value={formatMoney(paid._sum.amount)} detail="Acumulado registrado" icon={CircleDollarSign} /></section>
    <section className="module-panel portal-section"><div className="module-toolbar"><div><h2>Comprobantes por aprobar</h2><p>Pagos enviados por socios desde su portal</p></div></div>{submissions.length === 0 ? <EmptyState icon={ReceiptText} title="No hay comprobantes pendientes" description="Los nuevos desprendibles enviados por socios aparecerán aquí." /> : <div className="table-wrap module-table"><table><thead><tr><th>Socio</th><th>Venta</th><th>Programa</th><th>Concepto</th><th>Monto</th><th>Enviado</th><th>Archivo</th><th>Revisión</th></tr></thead><tbody>{submissions.map((submission) => <tr key={submission.id}><td>{submission.sale.member.firstName} {submission.sale.member.lastName}</td><td className="money">{submission.sale.code}</td><td>{submission.sale.program.name}</td><td>{paymentConceptLabels[submission.concept]}</td><td className="money">{formatMoney(submission.amount)}</td><td>{formatDate(submission.submittedAt)}</td><td><a className="row-action row-action-icon" href={submission.voucherUrl} target="_blank" rel="noreferrer" aria-label="Ver comprobante" title="Ver comprobante"><Eye size={17} aria-hidden="true" /></a></td><td><SubmissionReview id={submission.id} saleCode={submission.sale.code} amount={formatMoney(submission.amount)} voucherUrl={submission.voucherUrl} /></td></tr>)}</tbody></table></div>}</section>
    <section className="module-panel payments-register-panel"><div className="module-toolbar"><div><h2>Registro de pagos</h2><p>Movimientos confirmados y anulados conservados para auditoría</p></div></div>{payments.length === 0 ? <EmptyState icon={ReceiptText} title="No hay pagos registrados" description="Los pagos confirmados aparecerán aquí con sus acciones contables." /> : <div className="table-wrap module-table"><table><thead><tr><th>Referencia</th><th>Socio</th><th>Venta</th><th>Concepto</th><th>Monto</th><th>Fecha</th><th>Soporte</th><th>Estado</th><th></th></tr></thead><tbody>{payments.map((payment) => <tr key={payment.id}><td className="money">{payment.reference}</td><td>{payment.sale.member.firstName} {payment.sale.member.lastName}</td><td>{payment.sale.code}</td><td>{paymentConceptLabels[payment.concept]}</td><td className="money">{formatMoney(payment.amount)}</td><td>{formatDate(payment.paidAt)}</td><td>{payment.submission ? <a className="row-action row-action-icon" href={payment.submission.voucherUrl} target="_blank" rel="noreferrer" aria-label={`Ver soporte del pago ${payment.reference}`} title="Ver soporte"><Eye size={17} aria-hidden="true" /></a> : <PaymentVoucherAttach paymentId={payment.id} reference={payment.reference} />}</td><td><StatusPill tone={statusTone(payment.status)}>{payment.status === "CONFIRMED" ? "Confirmado" : "Anulado"}</StatusPill></td><td><PaymentManageDialog sales={saleOptions} payment={{ id: payment.id, saleId: payment.saleId, reference: payment.reference, amount: Number(payment.amount), concept: payment.concept, paidAt: payment.paidAt.toISOString().slice(0, 10), status: payment.status, history: (historyByPayment.get(payment.id) ?? []).map((item) => ({ id: item.id.toString(), action: item.action, createdAt: formatDate(item.createdAt) })) }} /></td></tr>)}</tbody></table></div>}</section>
  </>;
}
