"use client";

import { useActionState, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { FilePlus2, LoaderCircle, Plus, Save, X } from "lucide-react";
import { createContractTemplateAction, generateContractAction, updateContractAction, type ContractState } from "./actions";

const initial: ContractState = { success: false, message: "" };
const defaultContent = `CONTRATO DE PARTICIPACIÓN\n\nEntre Malabrigo Club Resort y {{NOMBRE_SOCIO}}, identificado con {{DOCUMENTO}}, código de socio {{CODIGO_SOCIO}}, se celebra el presente contrato correspondiente a la venta {{CODIGO_VENTA}}.\n\nPrograma: {{PROGRAMA}}\nValor: {{VALOR}}\nModalidad: {{MODALIDAD}}\nFecha: {{FECHA}}\n\nLas partes declaran conocer y aceptar las condiciones del programa y sus anexos.`;
type Option = { id: string; label: string };

function Modal({ title, subtitle, onClose, children }: { title: string; subtitle: string; onClose: () => void; children: React.ReactNode }) { return <div className="dialog-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="member-dialog" role="dialog" aria-modal="true" aria-labelledby="contract-dialog-title"><div className="dialog-header"><div><span className="eyebrow">Documentación legal</span><h2 id="contract-dialog-title">{title}</h2><p>{subtitle}</p></div><button className="icon-button" type="button" aria-label="Cerrar" onClick={onClose}><X size={18} /></button></div>{children}</section></div>; }
function Feedback({ state }: { state: ContractState }) { return state.message ? <p className={`form-message ${state.success ? "success" : "error"}`} aria-live="polite">{state.message}</p> : null; }

export function ContractActions({ templates, sales }: { templates: Option[]; sales: Option[] }) {
  const [mode, setMode] = useState<"template" | "generate" | null>(null); const router = useRouter();
  const [templateState, templateAction, templatePending] = useActionState(createContractTemplateAction, initial);
  const [generationState, generationAction, generationPending] = useActionState(generateContractAction, initial);
  useEffect(() => { if (templateState.success || generationState.success) router.refresh(); }, [templateState.success, generationState.success, router]);
  return <><button className="secondary-button" type="button" onClick={() => setMode("generate")} disabled={!templates.length || !sales.length}><FilePlus2 size={17} />Generar contrato</button><button className="primary-button" type="button" onClick={() => setMode("template")}><Plus size={17} />Nueva plantilla</button>
    {mode === "template" && <Modal title="Nueva plantilla" subtitle="Crea una versión reutilizable con campos automáticos." onClose={() => setMode(null)}><form action={templateAction} className="member-form"><div className="form-grid"><label><span>Código *</span><input name="code" placeholder="CONTRATO_VIP" required /></label><label><span>Nombre *</span><input name="name" placeholder="Contrato de participación" required /></label><label className="form-wide"><span>Contenido *</span><textarea name="content" rows={14} defaultValue={defaultContent} required /></label></div><small>Campos disponibles: {"{{NOMBRE_SOCIO}}, {{DOCUMENTO}}, {{CODIGO_SOCIO}}, {{CODIGO_VENTA}}, {{PROGRAMA}}, {{VALOR}}, {{MODALIDAD}}, {{FECHA}}"}</small><Feedback state={templateState} /><div className="dialog-actions"><button className="cancel-button" type="button" onClick={() => setMode(null)}>Cancelar</button><button className="primary-button" disabled={templatePending}>{templatePending ? <LoaderCircle className="spinner" size={17} /> : <Save size={17} />}Crear plantilla</button></div></form></Modal>}
    {mode === "generate" && <Modal title="Generar contrato" subtitle="Asocia la plantilla vigente a una venta registrada." onClose={() => setMode(null)}><form action={generationAction} className="member-form"><div className="form-grid"><label className="form-wide"><span>Venta *</span><select name="saleId" required defaultValue=""><option value="" disabled>Selecciona una venta</option>{sales.map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label className="form-wide"><span>Plantilla *</span><select name="templateId" required defaultValue=""><option value="" disabled>Selecciona una plantilla</option>{templates.map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label></div><Feedback state={generationState} /><div className="dialog-actions"><button className="cancel-button" type="button" onClick={() => setMode(null)}>Cancelar</button><button className="primary-button" disabled={generationPending}>{generationPending ? <LoaderCircle className="spinner" size={17} /> : <FilePlus2 size={17} />}Generar</button></div></form></Modal>}
  </>;
}

export function ContractManage({ contract }: { contract: { id: string; status: string } }) {
  const [open, setOpen] = useState(false); const [state, action, pending] = useActionState(updateContractAction.bind(null, contract.id), initial); const router = useRouter();
  useEffect(() => { if (state.success) router.refresh(); }, [state.success, router]);
  return <><button className="row-action" type="button" onClick={() => setOpen(true)}>Gestionar</button>{open && <Modal title="Gestionar contrato" subtitle="Actualiza el envío, firma o anulación del documento." onClose={() => setOpen(false)}><form action={action} className="member-form"><div className="form-grid"><label><span>Estado *</span><select name="status" defaultValue={contract.status === "DRAFT" ? "GENERATED" : contract.status}><option value="GENERATED">Generado</option><option value="SENT">Enviado</option><option value="SIGNED">Firmado</option><option value="VOIDED">Anulado</option></select></label><label><span>Contrato firmado PDF</span><input type="file" name="signedFile" accept="application/pdf" /></label></div><Feedback state={state} /><div className="dialog-actions"><button className="cancel-button" type="button" onClick={() => setOpen(false)}>Cancelar</button><button className="primary-button" disabled={pending}>{pending ? <LoaderCircle className="spinner" size={17} /> : <Save size={17} />}Guardar</button></div></form></Modal>}</>;
}
