"use server";
import { randomUUID } from "node:crypto";
import { mkdir, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireUser } from "@/lib/access-control";
import { db } from "@/lib/db";
export type OwnDocumentState = { success: boolean; message: string };
const schema = z.object({ title: z.string().trim().min(3).max(180), category: z.enum(["IDENTITY", "SEPARATION_FORM", "SEPARATION_PROOF", "SALE_PROOF", "SIGNED_CONTRACT", "ANNEX", "OTHER"]), saleId: z.string().uuid().or(z.literal("")) });
const types: Record<string, string> = { "image/jpeg": "jpg", "image/png": "png", "application/pdf": "pdf" };
export async function uploadOwnDocumentAction(_previous: OwnDocumentState, formData: FormData): Promise<OwnDocumentState> { const user = await requireUser(); if (!user.member) return { success: false, message: "Tu cuenta no tiene un expediente asociado." }; const parsed = schema.safeParse({ title: formData.get("title"), category: formData.get("category"), saleId: formData.get("saleId") ?? "" }); if (!parsed.success) return { success: false, message: "Completa el título, categoría y venta." }; if (parsed.data.saleId && !(await db.sale.findFirst({ where: { id: parsed.data.saleId, memberId: user.member.id } }))) return { success: false, message: "La inversión no pertenece a tu cuenta." }; const file = formData.get("file"); if (!(file instanceof File) || !file.size) return { success: false, message: "Selecciona un archivo." }; if (!types[file.type] || file.size > 12 * 1024 * 1024) return { success: false, message: "Usa JPG, PNG o PDF de máximo 12 MB." }; const fileName = `${randomUUID()}.${types[file.type]}`; const directory = path.join(process.cwd(), "public", "uploads", "member-documents"); const destination = path.join(directory, fileName); try { await mkdir(directory, { recursive: true }); await writeFile(destination, Buffer.from(await file.arrayBuffer())); const document = await db.documentRecord.create({ data: { memberId: user.member.id, saleId: parsed.data.saleId || null, uploadedById: user.id, title: parsed.data.title, category: parsed.data.category, visibility: "PRIVATE_MEMBER", status: "PENDING", url: `/uploads/member-documents/${fileName}` } }); await db.auditLog.create({ data: { actorUserId: user.id, action: "MEMBER_DOCUMENT_SUBMITTED", entityType: "DocumentRecord", entityId: document.id, after: { category: document.category, title: document.title } } }); } catch { await unlink(destination).catch(() => undefined); return { success: false, message: "No fue posible enviar el documento." }; } revalidatePath("/mi-portal/documentos"); revalidatePath("/socios"); return { success: true, message: "Documento enviado para validación." }; }
