import { connection } from "next/server";
import { Building2, Eye, Files, FolderOpen } from "lucide-react";
import { EmptyState, MetricCard, PageHeader, StatusPill } from "@/components/module-ui";
import { requireUser } from "@/lib/access-control";
import { db } from "@/lib/db";
import { formatDate, statusTone } from "@/lib/format";
import { RequestedDocumentUpload } from "./requested-document-upload";

const labels: Record<string, string> = { IDENTITY: "Identidad / DNI", SEPARATION_FORM: "Ficha de separación", SEPARATION_PROOF: "Comprobante de separación", SALE_PROOF: "Comprobante de pago", SIGNED_CONTRACT: "Contrato firmado", ANNEX: "Anexo", OTHER: "Otro" };
const statusLabels: Record<string, string> = { REQUESTED: "Por cargar", PENDING: "En revisión", APPROVED: "Aprobado", REJECTED: "Rechazado", CANCELLED: "Cancelado" };
const subjectLabels: Record<string, string> = { SALE: "Venta", PRIMARY_HOLDER: "Titular principal", HOLDER: "Titular", BENEFICIARY: "Beneficiario" };
const documentFields = { id: true, title: true, category: true, status: true, createdAt: true, url: true } as const;

export default async function OwnDocumentsPage() {
  const user = await requireUser();
  if (!user.member) return <EmptyState icon={Files} title="Sin expediente" description="Tu cuenta no tiene un socio asociado." />;
  await connection();
  const [legacyDocuments, companyDocuments, sales] = await Promise.all([
    db.documentRecord.findMany({ where: { memberId: user.member.id }, orderBy: { createdAt: "desc" }, select: documentFields }),
    db.documentRecord.findMany({ where: { memberId: null, visibility: "ALL_MEMBERS", status: "APPROVED" }, orderBy: { createdAt: "desc" }, select: documentFields }),
    db.sale.findMany({ where: { memberId: user.member.id, status: { not: "CANCELLED" } }, orderBy: { createdAt: "desc" }, select: { id: true, code: true, program: { select: { name: true } }, dossierDocuments: { orderBy: { createdAt: "desc" }, select: { id: true, title: true, category: true, subjectKind: true, subjectName: true, status: true, rejectionReason: true, fileName: true, createdAt: true } }, paymentSubmissions: { orderBy: { submittedAt: "desc" }, select: { id: true, amount: true, status: true, submittedAt: true } } } }),
  ]);
  const all = sales.flatMap((sale) => sale.dossierDocuments);
  const needingUpload = all.filter((item) => item.status === "REQUESTED" || item.status === "REJECTED").length;
  return <><PageHeader eyebrow="Portal del inversionista" title="Mis documentos" description="Atiende las solicitudes de tu expediente por inversión y consulta el estado de cada archivo." />
    <section className="module-metrics"><MetricCard label="Documentos solicitados" value={String(needingUpload)} detail="Por cargar o corregir" icon={FolderOpen} /><MetricCard label="En revisión" value={String(all.filter((item) => item.status === "PENDING").length)} detail="Pendientes de administración" icon={Files} /><MetricCard label="Biblioteca" value={String(companyDocuments.length)} detail="Documentos institucionales" icon={Building2} /></section>
    <section className="module-panel portal-section"><div className="module-toolbar"><div><h2>Solicitudes de documentos</h2><p>Administración indicará qué documento necesita para cada venta, titular o beneficiario. Solo podrás enviar archivos solicitados.</p></div></div><div className="dossier-list">{sales.flatMap((sale) => sale.dossierDocuments.map((item) => <article className="dossier-item" key={item.id}><div className="dossier-item-main"><div><strong>{item.title}</strong><span className={`dossier-status dossier-status-${item.status.toLowerCase()}`}>{statusLabels[item.status]}</span></div><p>{sale.code} · {sale.program.name} · {subjectLabels[item.subjectKind]}: {item.subjectName} · {labels[item.category] ?? item.category}</p>{item.status === "REJECTED" && <p className="dossier-reason">Motivo del rechazo: {item.rejectionReason || "Consulta con administración."}</p>}{item.fileName && <small>Archivo enviado: {item.fileName} · {formatDate(item.createdAt)}</small>}</div><div className="dossier-item-actions">{item.fileName && <a className="row-action row-action-icon" href={`/expediente/archivo/${item.id}`} target="_blank" rel="noreferrer" title="Ver archivo" aria-label={`Ver ${item.title}`}><Eye size={17} /></a>}{(item.status === "REQUESTED" || item.status === "REJECTED") && <RequestedDocumentUpload documentId={item.id} title={item.title} />}</div></article>))}</div>{all.length === 0 && <EmptyState icon={FolderOpen} title="Sin solicitudes" description="Por ahora administración no ha solicitado documentos de tus inversiones." />}</section>
    {sales.some((sale) => sale.paymentSubmissions.length > 0) && <section className="module-panel portal-section"><div className="module-toolbar"><div><h2>Comprobantes de pago</h2><p>Soportes asociados a cada venta. Su validación se realiza en Pagos.</p></div></div><div className="dossier-list">{sales.flatMap((sale) => sale.paymentSubmissions.map((item) => <article className="dossier-item" key={item.id}><div className="dossier-item-main"><strong>{sale.code} · USD {Number(item.amount).toLocaleString("en-US")}</strong><p>{sale.program.name} · {item.status === "APPROVED" ? "Aprobado" : item.status === "REJECTED" ? "Rechazado" : "Por revisar"} · {formatDate(item.submittedAt)}</p></div><a className="row-action row-action-icon" href={`/pagos/comprobantes/${item.id}`} target="_blank" rel="noreferrer" title="Ver comprobante" aria-label="Ver comprobante"><Eye size={17} /></a></article>))}</div></section>}
    {legacyDocuments.length > 0 && <section className="module-panel portal-section"><div className="module-toolbar"><div><h2>Documentos anteriores</h2><p>Archivos registrados antes del expediente por venta; se conservan para consulta.</p></div></div><div className="table-wrap module-table"><table><thead><tr><th>Título</th><th>Categoría</th><th>Estado</th><th>Fecha</th><th>Archivo</th></tr></thead><tbody>{legacyDocuments.map((item) => <tr key={item.id}><td>{item.title}</td><td>{labels[item.category] ?? item.category}</td><td><StatusPill tone={statusTone(item.status)}>{item.status === "PENDING" ? "Por validar" : item.status === "APPROVED" ? "Aprobado" : "Rechazado"}</StatusPill></td><td>{formatDate(item.createdAt)}</td><td><a className="row-action row-action-icon" href={item.url} target="_blank" rel="noreferrer" aria-label={`Abrir ${item.title}`} title="Abrir documento"><Eye size={17} /></a></td></tr>)}</tbody></table></div></section>}
    <section className="module-panel portal-section"><div className="module-toolbar"><div><h2>Biblioteca del proyecto</h2><p>Renders, planos, cronograma y documentos oficiales.</p></div></div>{companyDocuments.length ? <div className="document-grid">{companyDocuments.map((item) => <a href={item.url} target="_blank" rel="noreferrer" key={item.id}><Files size={22} /><div><strong>{item.title}</strong><span>{labels[item.category] ?? item.category} · {formatDate(item.createdAt)}</span></div></a>)}</div> : <EmptyState icon={Building2} title="Sin documentos publicados" description="La empresa publicará aquí la información oficial del proyecto." />}</section></>;
}
