import { connection } from "next/server";
import { Building2, FileArchive, Files } from "lucide-react";
import { EmptyState, MetricCard, PageHeader, StatusPill } from "@/components/module-ui";
import { requirePermission } from "@/lib/access-control";
import { db } from "@/lib/db";
import { formatDate } from "@/lib/format";
import { DocumentDialog } from "./document-dialog";
const labels: Record<string, string> = { RENDER: "Render", PROJECT: "Proyecto", TIMELINE: "Línea de tiempo", CONSTRUCTION_PROGRESS: "Avance de obra", CABINS: "Cabañas", PLANS: "Planos", CONTRACT_MODEL: "Modelo de contrato", OTHER: "Otro" };
export default async function DocumentsPage() { await requirePermission("CONTRACTS"); await connection(); const documents = await db.documentRecord.findMany({ where: { memberId: null }, orderBy: { createdAt: "desc" }, include: { uploadedBy: true } }); return <><PageHeader eyebrow="Repositorio" title="Documentos del proyecto" description="Renders, planos, cronograma, modelos y archivos institucionales." action={<DocumentDialog />} /><section className="module-metrics"><MetricCard label="Documentos" value={String(documents.length)} detail="Archivos registrados" icon={Files} /><MetricCard label="Visibles para socios" value={String(documents.filter((item) => item.visibility === "ALL_MEMBERS").length)} detail="Repositorio público interno" icon={Building2} /><MetricCard label="Solo administración" value={String(documents.filter((item) => item.visibility === "ADMIN_ONLY").length)} detail="Acceso restringido" icon={FileArchive} /></section><section className="module-panel"><div className="module-toolbar"><div><h2>Biblioteca institucional</h2><p>Documentación oficial clasificada</p></div></div>{documents.length ? <div className="table-wrap module-table"><table><thead><tr><th>Título</th><th>Categoría</th><th>Visibilidad</th><th>Publicado por</th><th>Fecha</th><th>Archivo</th></tr></thead><tbody>{documents.map((item) => <tr key={item.id}><td>{item.title}</td><td>{labels[item.category] ?? item.category}</td><td><StatusPill tone={item.visibility === "ALL_MEMBERS" ? "success" : "neutral"}>{item.visibility === "ALL_MEMBERS" ? "Todos los socios" : "Administración"}</StatusPill></td><td>{item.uploadedBy?.displayName ?? "Sistema"}</td><td>{formatDate(item.createdAt)}</td><td><a className="row-action" href={item.url} target="_blank" rel="noreferrer">Abrir</a></td></tr>)}</tbody></table></div> : <EmptyState icon={Files} title="Repositorio vacío" description="Publica renders, proyecto, línea de tiempo, planos y modelos oficiales." />}</section></>; }
