import { connection } from "next/server";
import { Award, BarChart3, CircleDollarSign, FileCheck2, Network, PieChart, Trophy, UsersRound } from "lucide-react";
import { EmptyState, MetricCard, PageHeader } from "@/components/module-ui";
import { db } from "@/lib/db";
import { requirePermission } from "@/lib/access-control";
import { formatMoney } from "@/lib/format";

export default async function ReportsPage() {
  await requirePermission("REPORTS"); await connection();
  const featuredProject = await db.constructionProject.findFirst({ where: { active: true }, orderBy: { createdAt: "asc" }, select: { id: true, name: true } });
  const [members, sales, payments, shares, programs, commissions, ranks, ambassadors, contracts, documents, awards, stages] = await Promise.all([
    db.member.count(), db.sale.count(), db.payment.aggregate({ where: { status: "CONFIRMED" }, _sum: { amount: true } }), db.shareAllocation.aggregate({ _sum: { quantity: true } }),
    db.program.findMany({ orderBy: { cashPrice: "asc" }, include: { sales: { select: { totalPrice: true, status: true } } } }),
    db.commissionEntry.groupBy({ by: ["status"], _sum: { amount: true }, _count: true }), db.rankDefinition.findMany({ orderBy: { sortOrder: "asc" } }),
    db.ambassadorProfile.findMany({ select: { currentRank: true } }), db.contract.groupBy({ by: ["status"], _count: true }), db.documentRecord.groupBy({ by: ["visibility", "status"], _count: true }), db.rankAward.groupBy({ by: ["status"], _count: true }),
    db.projectStage.findMany({ where: { projectId: featuredProject?.id ?? "00000000-0000-0000-0000-000000000000" }, include: { updates: { orderBy: { occurredAt: "desc" }, take: 1 } } }),
  ]);
  const issuedShares = shares._sum.quantity ?? 0; const capacity = 2250000;
  const commissionTotal = commissions.filter((item) => item.status !== "REVERSED").reduce((sum, item) => sum + Number(item._sum.amount ?? 0), 0);
  const projectProgress = stages.length ? stages.reduce((sum, stage) => sum + Number(stage.weight) * Number(stage.updates[0]?.progress ?? 0), 0) / 100 : 0;
  return <><PageHeader eyebrow="Inteligencia operativa" title="Reportes" description="Indicadores comerciales, financieros, documentales y de la red de embajadores." />
    <section className="module-metrics"><MetricCard label="Socios" value={String(members)} detail="Expedientes registrados" icon={UsersRound} /><MetricCard label="Ventas" value={String(sales)} detail="Operaciones totales" icon={BarChart3} /><MetricCard label="Cobranza" value={formatMoney(payments._sum.amount)} detail="Pagos confirmados" icon={CircleDollarSign} /><MetricCard label="Comisiones" value={formatMoney(commissionTotal)} detail="Directas e indirectas" icon={Network} /></section>
    <section className="report-grid"><article className="module-panel"><div className="module-toolbar"><div><h2>Ventas por programa</h2><p>Operaciones y volumen contratado</p></div></div><div className="program-report">{programs.map((program) => <div key={program.id}><span><strong>{program.name}</strong><small>{program.sales.length} ventas · {formatMoney(program.sales.filter((sale) => sale.status !== "CANCELLED").reduce((sum, sale) => sum + Number(sale.totalPrice), 0))}</small></span><b>{formatMoney(program.cashPrice)}</b></div>)}</div></article><article className="module-panel report-capacity"><span className="panel-kicker">Capital accionario</span><h2>Control de emisión</h2><div className="capacity-number"><strong>{((issuedShares / capacity) * 100).toFixed(2)}%</strong><span>del límite utilizado</span></div><div className="capacity-bar"><i style={{ width: `${Math.min(100, issuedShares / capacity * 100)}%` }} /></div><p>{issuedShares.toLocaleString("es-PE")} asignadas · {(capacity - issuedShares).toLocaleString("es-PE")} disponibles.</p></article></section>

    <section className="report-grid portal-section"><article className="module-panel"><div className="module-toolbar"><div><h2>Rangos de embajadores</h2><p>Distribución actual de carrera</p></div></div><div className="settings-list">{ranks.map((rank) => <div key={rank.code}><span><strong>{rank.name}</strong><small>{rank.rewardName ?? "Sin premio configurado"}</small></span><b>{ambassadors.filter((item) => item.currentRank === rank.code).length}</b></div>)}</div></article><article className="module-panel"><div className="module-toolbar"><div><h2>Estado de comisiones</h2><p>Control del pasivo comercial</p></div></div>{commissions.length ? <div className="settings-list">{commissions.map((item) => <div key={item.status}><span><strong>{item.status === "PENDING" ? "Pendientes" : item.status === "APPROVED" ? "Aprobadas" : item.status === "PAID" ? "Pagadas" : "Reversadas"}</strong><small>{item._count} movimientos</small></span><b>{formatMoney(item._sum.amount)}</b></div>)}</div> : <EmptyState icon={Network} title="Sin comisiones" description="No hay movimientos para consolidar." />}</article></section>

    <section className="module-metrics portal-section"><MetricCard label="Contratos firmados" value={String(contracts.find((item) => item.status === "SIGNED")?._count ?? 0)} detail={`${contracts.reduce((sum, item) => sum + item._count, 0)} contratos totales`} icon={FileCheck2} /><MetricCard label="Documentos" value={String(documents.reduce((sum, item) => sum + item._count, 0))} detail={`${documents.filter((item) => item.status === "PENDING").reduce((sum, item) => sum + item._count, 0)} por validar`} icon={PieChart} /><MetricCard label="Premios" value={String(awards.reduce((sum, item) => sum + item._count, 0))} detail={`${awards.filter((item) => item.status !== "DELIVERED").reduce((sum, item) => sum + item._count, 0)} por entregar`} icon={Award} /><MetricCard label="Avance de obra" value={`${projectProgress.toFixed(1)}%`} detail={`${featuredProject?.name ?? "Sin proyecto"} · ${stages.length} etapas`} icon={Trophy} /></section>
  </>;
}
