import { FileCheck2, Landmark, UsersRound, WalletCards } from "lucide-react";
import { EmptyState, MetricCard, PageHeader, StatusPill } from "@/components/module-ui";
import { requireUser, roleCodes } from "@/lib/access-control";
import { db } from "@/lib/db";
import { formatDate, formatMoney, saleStatusLabel, statusTone } from "@/lib/format";
import { redirect } from "next/navigation";

export default async function MyPortalPage() {
  const user = await requireUser();
  if (!roleCodes(user).includes("MEMBER") || !user.member?.investorProfile) redirect("/mi-red");
  const member = await db.member.findUniqueOrThrow({ where: { id: user.member.id }, include: { beneficiaries: { orderBy: { createdAt: "asc" } }, documents: true, sales: { orderBy: { createdAt: "desc" }, include: { program: true, payments: { where: { status: "CONFIRMED" } }, contracts: true, shareAllocation: true, stayAllocation: true } } } });
  const payments = member.sales.flatMap((sale) => sale.payments); const contracts = member.sales.flatMap((sale) => sale.contracts);
  return <><PageHeader eyebrow="Portal del inversionista" title="Mis inversiones" description={`${member.firstName}, aquí solo se muestra tu información personal y contractual.`} />
    <section className="module-metrics"><MetricCard label="Programas" value={String(member.sales.length)} detail="Inversiones registradas" icon={Landmark} /><MetricCard label="Pagos confirmados" value={formatMoney(payments.reduce((sum, payment) => sum + Number(payment.amount), 0))} detail={`${payments.length} movimientos`} icon={WalletCards} /><MetricCard label="Contratos" value={String(contracts.length)} detail="Documentos asociados" icon={FileCheck2} /><MetricCard label="Beneficiarios" value={String(member.beneficiaries.length)} detail="Personas registradas" icon={UsersRound} /></section>
    <section className="module-panel"><div className="module-toolbar"><div><h2>Mis programas</h2><p>Condiciones, beneficios y estado de cada inversión</p></div></div>{member.sales.length === 0 ? <EmptyState icon={Landmark} title="No tienes inversiones registradas" description="Cuando se registre una venta a tu nombre aparecerá en este espacio." /> : <div className="table-wrap module-table"><table><thead><tr><th>Venta</th><th>Programa</th><th>Membresía</th><th>Modalidad</th><th>Valor</th><th>Pagado</th><th>Acciones / días</th><th>Estado</th><th>Fecha</th></tr></thead><tbody>{member.sales.map((sale) => <tr key={sale.id}><td className="money">{sale.code}</td><td>{sale.program.name}<small className="cell-secondary">{sale.program.shareholderCategory ?? sale.program.observations ?? "Programa de participación"}</small></td><td>{sale.program.membershipName ?? "—"}</td><td>{sale.mode === "CASH" ? "Contado" : "Crédito"}</td><td className="money">{formatMoney(sale.totalPrice)}</td><td className="money">{formatMoney(sale.payments.reduce((sum, payment) => sum + Number(payment.amount), 0))}</td><td>{sale.shareAllocation?.quantity ? `${sale.shareAllocation.quantity} acciones` : sale.stayAllocation?.days ? `${sale.stayAllocation.days} días` : "Pendiente"}</td><td><StatusPill tone={statusTone(sale.status)}>{saleStatusLabel[sale.status]}</StatusPill></td><td>{formatDate(sale.createdAt)}</td></tr>)}</tbody></table></div>}</section>
    <section className="module-panel portal-section"><div className="module-toolbar"><div><h2>Beneficiarios y sociedad conyugal</h2><p>Información registrada en tu expediente.</p></div></div>{member.beneficiaries.length ? <div className="table-wrap module-table"><table><thead><tr><th>Nombre</th><th>Documento</th><th>Relación</th><th>Condición</th></tr></thead><tbody>{member.beneficiaries.map((item) => <tr key={item.id}><td>{item.fullName}</td><td>{item.document ?? "—"}</td><td>{item.relationship}</td><td>{item.isSpouse ? "Cónyuge / cotitular" : "Beneficiario"}</td></tr>)}</tbody></table></div> : <EmptyState icon={UsersRound} title="Sin beneficiarios registrados" description="Solicita a administración la actualización de tu expediente." />}</section>
  </>;
}
