import { FileCheck2, Landmark, UsersRound, WalletCards } from "lucide-react";
import { EmptyState, MetricCard, PageHeader, StatusPill } from "@/components/module-ui";
import { requireUser, roleCodes } from "@/lib/access-control";
import { db } from "@/lib/db";
import { formatDate, formatMoney, saleStatusLabel, statusTone } from "@/lib/format";
import { redirect } from "next/navigation";

export default async function MyPortalPage() {
  const user = await requireUser();
  if (!roleCodes(user).includes("MEMBER") || !user.member?.investorProfile) redirect("/mi-red");
  const member = await db.member.findUniqueOrThrow({ where: { id: user.member.id }, include: { documents: true, sales: { orderBy: { createdAt: "desc" }, include: { program: true, beneficiaries: { orderBy: { createdAt: "asc" } }, payments: { where: { status: "CONFIRMED" } }, contracts: true, shareAllocation: true, stayAllocation: true } } } });
  const payments = member.sales.flatMap((sale) => sale.payments); const contracts = member.sales.flatMap((sale) => sale.contracts);
  return <><PageHeader eyebrow="Portal del inversionista" title="Mis inversiones" description={`${member.firstName}, aquí solo se muestra tu información personal y contractual.`} />
    <section className="module-metrics"><MetricCard label="Programas" value={String(member.sales.length)} detail="Inversiones registradas" icon={Landmark} /><MetricCard label="Pagos confirmados" value={formatMoney(payments.reduce((sum, payment) => sum + Number(payment.amount), 0))} detail={`${payments.length} movimientos`} icon={WalletCards} /><MetricCard label="Contratos" value={String(contracts.length)} detail="Documentos asociados" icon={FileCheck2} /><MetricCard label="Beneficiarios" value={String(member.sales.filter((sale) => sale.status !== "CANCELLED").flatMap((sale) => sale.beneficiaries).filter((person) => !person.isHolder).length)} detail="Asignaciones en programas" icon={UsersRound} /></section>
    <section className="module-panel"><div className="module-toolbar"><div><h2>Mis programas</h2><p>Condiciones, beneficios y estado de cada inversión</p></div></div>{member.sales.length === 0 ? <EmptyState icon={Landmark} title="No tienes inversiones registradas" description="Cuando se registre una venta a tu nombre aparecerá en este espacio." /> : <div className="table-wrap module-table"><table><thead><tr><th>Venta</th><th>Programa</th><th>Membresía</th><th>Modalidad</th><th>Valor</th><th>Pagado</th><th>Acciones / días</th><th>Estado</th><th>Fecha</th></tr></thead><tbody>{member.sales.map((sale) => <tr key={sale.id}><td className="money">{sale.code}</td><td>{sale.program.name}<small className="cell-secondary">{sale.program.shareholderCategory ?? sale.program.observations ?? "Programa de participación"}</small></td><td>{sale.program.membershipName ?? "—"}</td><td>{sale.mode === "CASH" ? "Contado" : "Crédito"}</td><td className="money">{formatMoney(sale.totalPrice)}</td><td className="money">{formatMoney(sale.payments.reduce((sum, payment) => sum + Number(payment.amount), 0))}</td><td>{sale.shareAllocation?.quantity ? `${sale.shareAllocation.quantity} acciones` : sale.stayAllocation?.days ? `${sale.stayAllocation.days} días` : "Pendiente"}</td><td><StatusPill tone={statusTone(sale.status)}>{saleStatusLabel[sale.status]}</StatusPill></td><td>{formatDate(sale.createdAt)}</td></tr>)}</tbody></table></div>}</section>
    <section className="module-panel portal-section"><div className="module-toolbar"><div><h2>Titulares y beneficiarios</h2><p>Personas asignadas por separado a cada programa.</p></div></div>{member.sales.filter((sale) => sale.status !== "CANCELLED").length ? <div className="investor-program-people">{member.sales.filter((sale) => sale.status !== "CANCELLED").map((sale) => <article key={sale.id}><div className="section-title"><div><h3>{sale.program.name} · {sale.code}</h3><p>{sale.ownershipType === "MARRIED" ? "Sociedad conyugal" : "Un contratante"}</p></div><span>{sale.beneficiaries.filter((person) => person.isHolder).length + 1} titulares · {sale.beneficiaries.filter((person) => !person.isHolder).length} beneficiarios</span></div><div className="table-wrap module-table"><table><thead><tr><th>Nombre</th><th>Documento</th><th>Relación</th><th>Condición</th></tr></thead><tbody><tr><td>{member.firstName} {member.lastName}</td><td>{member.documentNumber}</td><td>Socio principal</td><td>Titular principal</td></tr>{sale.beneficiaries.map((person) => <tr key={person.id}><td>{person.fullName}</td><td>{person.document ?? "—"}</td><td>{person.relationship}</td><td>{person.isHolder ? "Titular adicional" : "Beneficiario"}</td></tr>)}</tbody></table></div></article>)}</div> : <EmptyState icon={UsersRound} title="Sin programas vigentes" description="Las asignaciones aparecerán cuando se registre un programa." />}</section>
  </>;
}
