"use client";

import { useActionState, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { CalendarPlus, LoaderCircle, Upload, X } from "lucide-react";
import { createProjectStageAction, publishProjectUpdateAction, type ConstructionState } from "./actions";

const initial: ConstructionState = { success: false, message: "" };
type Stage = { id: string; name: string; progress: number };
export function ConstructionDialog({ stages }: { stages: Stage[] }) {
  const [open, setOpen] = useState(false); const [tab, setTab] = useState<"update" | "stage">(stages.length ? "update" : "stage"); const router = useRouter();
  const [stageState, stageAction, stagePending] = useActionState(createProjectStageAction, initial);
  const [updateState, updateAction, updatePending] = useActionState(publishProjectUpdateAction, initial);
  useEffect(() => { if (stageState.success || updateState.success) router.refresh(); }, [stageState.success, updateState.success, router]);
  const state = tab === "stage" ? stageState : updateState;
  return <><button className="primary-button" type="button" onClick={() => setOpen(true)}><Upload size={17} />Publicar avance</button>{open && <div className="dialog-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) setOpen(false); }}><section className="member-dialog" role="dialog" aria-modal="true" aria-labelledby="construction-dialog-title"><div className="dialog-header"><div><span className="eyebrow">Seguimiento de obra</span><h2 id="construction-dialog-title">Actualizar proyecto</h2><p>Configura el cronograma y publica evidencias para los socios.</p></div><button className="icon-button" aria-label="Cerrar" type="button" onClick={() => setOpen(false)}><X size={18} /></button></div><div className="program-selector" role="tablist"><button type="button" role="tab" aria-selected={tab === "update"} className={tab === "update" ? "active" : ""} disabled={!stages.length} onClick={() => setTab("update")}>Publicar avance</button><button type="button" role="tab" aria-selected={tab === "stage"} className={tab === "stage" ? "active" : ""} onClick={() => setTab("stage")}>Nueva etapa</button></div>
      {tab === "stage" ? <form action={stageAction} className="member-form"><div className="form-grid"><label><span>Nombre de la etapa *</span><input name="name" required /></label><label><span>Peso en el proyecto (%) *</span><input name="weight" type="number" min="0.01" max="100" step="0.01" required /></label><label><span>Fecha inicial</span><input name="startsAt" type="date" /></label><label><span>Fecha final</span><input name="endsAt" type="date" /></label><label className="form-wide"><span>Descripción</span><textarea name="description" rows={4} /></label></div>{state.message && <p className={`form-message ${state.success ? "success" : "error"}`}>{state.message}</p>}<div className="dialog-actions"><button className="cancel-button" type="button" onClick={() => setOpen(false)}>Cancelar</button><button className="primary-button" disabled={stagePending}>{stagePending ? <LoaderCircle className="spinner" size={17} /> : <CalendarPlus size={17} />}Crear etapa</button></div></form>
      : <form action={updateAction} className="member-form"><div className="form-grid"><label className="form-wide"><span>Etapa *</span><select name="stageId" required>{stages.map((stage) => <option value={stage.id} key={stage.id}>{stage.name} · {stage.progress}%</option>)}</select></label><label><span>Título *</span><input name="title" required /></label><label><span>Avance acumulado (%) *</span><input name="progress" type="number" min="0" max="100" step="0.1" required /></label><label><span>Fecha del avance *</span><input name="occurredAt" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required /></label><label><span>Evidencia</span><input name="media" type="file" accept=".jpg,.jpeg,.png,.webp,.pdf" /></label><label className="form-wide"><span>Descripción de la evidencia</span><input name="altText" /></label><label className="form-wide"><span>Descripción del avance *</span><textarea name="description" rows={5} required /></label></div>{state.message && <p className={`form-message ${state.success ? "success" : "error"}`}>{state.message}</p>}<div className="dialog-actions"><button className="cancel-button" type="button" onClick={() => setOpen(false)}>Cancelar</button><button className="primary-button" disabled={updatePending}>{updatePending ? <LoaderCircle className="spinner" size={17} /> : <Upload size={17} />}Publicar</button></div></form>}
    </section></div>}</>;
}
